name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -- CI PHASE --
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/actions/checkout@v4

    - name: Set up the Node.js Environment
      uses: actions/actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Automated Tests
      run: npm test